{{- if .Values.nodesocialnetwork.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "carsharing-helm-charts.secretName" . }}-nodesocialnetwork
  labels:
    {{- include "carsharing-helm-charts.labels" . | nindent 4 }}
    app: {{ include "carsharing-helm-charts.secretName" . }}-nodesocialnetwork
  {{- with .Values.nodesocialnetwork.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
data:
  .dockerconfigjson: {{ .Values.nodesocialnetwork.secret.docker_auth }}

type: kubernetes.io/dockerconfigjson