apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "carsharing-helm-charts.fullname" . }}-nodepython
  labels:
    {{- include "carsharing-helm-charts.labels" . | nindent 4 }}
    app: {{ include "carsharing-helm-charts.fullname" . }}-nodepython
spec:
  {{- if not .Values.nodepython.autoscaling.enabled }}
  replicas: {{ .Values.nodepython.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "carsharing-helm-charts.selectorLabels" . | nindent 6 }}
      app: {{ include "carsharing-helm-charts.fullname" . }}-nodepython
  template:
    metadata:
      {{- with .Values.nodepython.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "carsharing-helm-charts.selectorLabels" . | nindent 8 }}
        app: {{ include "carsharing-helm-charts.fullname" . }}-nodepython
    spec:
      imagePullSecrets:
        - name:  {{ include "carsharing-helm-charts.secretName" . }}-nodepython
      restartPolicy: Always
      containers:
        - args:
            - node
            - app.js
          env:
            - name: CACHE_CHECK_PERIOD
              valueFrom:
                configMapKeyRef:
                  key: CACHE_CHECK_PERIOD
                  name: {{ include "carsharing-helm-charts.fullname" . }}-nodepython-config
            - name: CACHE_TTL
              valueFrom:
                configMapKeyRef:
                  key: CACHE_TTL
                  name: {{ include "carsharing-helm-charts.fullname" . }}-nodepython-config
            - name: CARSHARING_API_HOST
              valueFrom:
                configMapKeyRef:
                  key: CARSHARING_API_HOST
                  name: {{ include "carsharing-helm-charts.fullname" . }}-nodepython-config
            - name: CITIES
              valueFrom:
                configMapKeyRef:
                  key: CITIES
                  name: {{ include "carsharing-helm-charts.fullname" . }}-nodepython-config
            - name: DEFAULT_TEMPERATURE
              valueFrom:
                configMapKeyRef:
                  key: DEFAULT_TEMPERATURE
                  name: {{ include "carsharing-helm-charts.fullname" . }}-nodepython-config
            - name: GEOCODE_FILE
              valueFrom:
                configMapKeyRef:
                  key: GEOCODE_FILE
                  name: {{ include "carsharing-helm-charts.fullname" . }}-nodepython-config
            - name: MAX_NUMBER_OF_REQUESTS
              valueFrom:
                configMapKeyRef:
                  key: MAX_NUMBER_OF_REQUESTS
                  name: {{ include "carsharing-helm-charts.fullname" . }}-nodepython-config
            - name: MINUTES_TO_LIMIT_REQUESTS
              valueFrom:
                configMapKeyRef:
                  key: MINUTES_TO_LIMIT_REQUESTS
                  name: {{ include "carsharing-helm-charts.fullname" . }}-nodepython-config
            - name: MODEL_FILE
              valueFrom:
                configMapKeyRef:
                  key: MODEL_FILE
                  name: {{ include "carsharing-helm-charts.fullname" . }}-nodepython-config
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  key: NODE_ENV
                  name: {{ include "carsharing-helm-charts.fullname" . }}-nodepython-config
            - name: PATH_MODEL_AND_DATA
              valueFrom:
                configMapKeyRef:
                  key: PATH_MODEL_AND_DATA
                  name: {{ include "carsharing-helm-charts.fullname" . }}-nodepython-config
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PORT
                  name: {{ include "carsharing-helm-charts.fullname" . }}-nodepython-config
            - name: PREDICTION_ALGORITHM_FILE
              valueFrom:
                configMapKeyRef:
                  key: PREDICTION_ALGORITHM_FILE
                  name: {{ include "carsharing-helm-charts.fullname" . }}-nodepython-config
            - name: RADIUS_NEAREST_LOCATION
              valueFrom:
                configMapKeyRef:
                  key: RADIUS_NEAREST_LOCATION
                  name: {{ include "carsharing-helm-charts.fullname" . }}-nodepython-config
            - name: RADIUS_NEAREST_LOCATION
              valueFrom:
                configMapKeyRef:
                  key: RADIUS_NEAREST_LOCATION
                  name: {{ include "carsharing-helm-charts.fullname" . }}-nodepython-config
            - name: SWAGGER_HOST
              valueFrom:
                configMapKeyRef:
                  key: SWAGGER_HOST
                  name: {{ include "carsharing-helm-charts.fullname" . }}-nodepython-config
            - name: WEATHER_APIKEY
              valueFrom:
                configMapKeyRef:
                  key: WEATHER_APIKEY
                  name: {{ include "carsharing-helm-charts.fullname" . }}-nodepython-config
            - name: WEATHER_APIKEY
              valueFrom:
                configMapKeyRef:
                  key: WEATHER_APIKEY
                  name: {{ include "carsharing-helm-charts.fullname" . }}-nodepython-config
            - name: WEATHER_API_URL
              valueFrom:
                configMapKeyRef:
                  key: WEATHER_API_URL
                  name: {{ include "carsharing-helm-charts.fullname" . }}-nodepython-config
          image: "{{ .Values.nodepython.image.repository }}:{{ .Values.nodepython.image.tag | default .Chart.AppVersion }}"
          name: {{ .Chart.Name }}-nodepython
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP

      {{- with .Values.nodepython.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodepython.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodepython.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}




