apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "carsharing-helm-charts.fullname" . }}-nodepython-config
  labels:
    {{- include "carsharing-helm-charts.labels" . | nindent 4 }}
    app: nodepython-config

data:
  NODE_ENV: {{ .Values.nodepython.environment.node_env | quote }}
  PORT: {{ .Values.nodepython.environment.port | quote }}
  MAX_NUMBER_OF_REQUESTS: {{ .Values.nodepython.environment.max_number_of_requests | quote }}
  MINUTES_TO_LIMIT_REQUESTS: {{ .Values.nodepython.environment.minutes_to_limit_requests | quote }}
  CACHE_TTL: {{ .Values.nodepython.environment.cache_ttl  | quote }}
  CACHE_CHECK_PERIOD: {{ .Values.nodepython.environment.cache_check_period  | quote }}
  SWAGGER_HOST: {{ .Values.nodepython.environment.swagger_host | quote }}
  CARSHARING_API_HOST: http://{{ include "carsharing-helm-charts.fullname" . }}-nodeapi:8080
  PATH_MODEL_AND_DATA: {{ .Values.nodepython.environment.path_model_and_data | quote }}
  MODEL_FILE: {{ .Values.nodepython.environment.model_file | quote }}
  GEOCODE_FILE: {{ .Values.nodepython.environment.geocode_file | quote }}
  PREDICTION_ALGORITHM_FILE: {{ .Values.nodepython.environment.prediction_algorithm_file | quote }}
  RADIUS_NEAREST_LOCATION: {{ .Values.nodepython.environment.radius_nearest_location | quote }}
  WEATHER_API_URL: {{ .Values.nodepython.environment.weather_api_url | quote }}
  WEATHER_APIKEY: {{ .Values.nodepython.environment.weather_apikey | quote }}
  DEFAULT_TEMPERATURE: {{ .Values.nodepython.environment.default_temperature | quote }}
  CITIES: {{ .Values.nodepython.environment.cities | quote }}
