{{- if .Values.nodeapi.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "carsharing-helm-charts.secretName" . }}-nodeapi
  labels:
    {{- include "carsharing-helm-charts.labels" . | nindent 4 }}
    app: {{ include "carsharing-helm-charts.secretName" . }}-nodeapi
  {{- with .Values.nodeapi.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
data:
  .dockerconfigjson: {{ .Values.nodeapi.secret.docker_auth }}

type: kubernetes.io/dockerconfigjson